// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum AudioState: Int {
  case stateOpen = 0
  case statePause = 1
  case stateClose = 2
}

enum LogLevel: Int {
  case logLevelVerbose = 0
  case logLevelDebug = 1
  case logLevelInfo = 2
  case logLevelWarning = 3
  case logLevelError = 4
  case logLevelNone = 5
}

enum VadMode: Int {
  case typeUnknown = 0
  case typeVad = 1
  case typeP2t = 2
  case typeKws = 3
  case typeParallel = 4
  case typeKws2Parallel = 5
  case typeAutoContinual = 6
  case typeKwsContinual = 7
  case typeKws2Talk = 8
  case typeOnlyKws = 9
}

private class FlutterAliyunNuiHostApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AudioState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return LogLevel(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return VadMode(rawValue: enumResultAsInt)
      }
      return nil
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class FlutterAliyunNuiHostApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AudioState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? LogLevel {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? VadMode {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else {
      super.writeValue(value)
    }
  }
}

private class FlutterAliyunNuiHostApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FlutterAliyunNuiHostApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FlutterAliyunNuiHostApiPigeonCodecWriter(data: data)
  }
}

class FlutterAliyunNuiHostApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = FlutterAliyunNuiHostApiPigeonCodec(readerWriter: FlutterAliyunNuiHostApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol FlutterAliyunNuiCallbackProtocol {
  func onNuiAudioStateChanged(state stateArg: AudioState, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onNuiEventCallback(event eventArg: String, resultCode resultCodeArg: Int64, kwsResult kwsResultArg: String, asrResult asrResultArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class FlutterAliyunNuiCallback: FlutterAliyunNuiCallbackProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: FlutterAliyunNuiHostApiPigeonCodec {
    return FlutterAliyunNuiHostApiPigeonCodec.shared
  }
  func onNuiAudioStateChanged(state stateArg: AudioState, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_aliyun_nui.FlutterAliyunNuiCallback.onNuiAudioStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onNuiEventCallback(event eventArg: String, resultCode resultCodeArg: Int64, kwsResult kwsResultArg: String, asrResult asrResultArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_aliyun_nui.FlutterAliyunNuiCallback.onNuiEventCallback\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg, resultCodeArg, kwsResultArg, asrResultArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FlutterAliyunNuiHostApi {
  func initialize(params: [String: Any?], saveLog: Bool, logLevel: LogLevel) throws -> Int64
  func setParams(params: [String: Any?]) throws -> Int64
  func startDialog(mode: VadMode, params: [String: Any?]) throws -> Int64
  func release() throws -> Int64
  func cancelDialog() throws -> Int64
  func stopDialog() throws -> Int64
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FlutterAliyunNuiHostApiSetup {
  static var codec: FlutterStandardMessageCodec { FlutterAliyunNuiHostApiPigeonCodec.shared }
  /// Sets up an instance of `FlutterAliyunNuiHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FlutterAliyunNuiHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_aliyun_nui.FlutterAliyunNuiHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let paramsArg = args[0] as! [String: Any?]
        let saveLogArg = args[1] as! Bool
        let logLevelArg = args[2] as! LogLevel
        do {
          let result = try api.initialize(params: paramsArg, saveLog: saveLogArg, logLevel: logLevelArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let setParamsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_aliyun_nui.FlutterAliyunNuiHostApi.setParams\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setParamsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let paramsArg = args[0] as! [String: Any?]
        do {
          let result = try api.setParams(params: paramsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setParamsChannel.setMessageHandler(nil)
    }
    let startDialogChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_aliyun_nui.FlutterAliyunNuiHostApi.startDialog\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startDialogChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let modeArg = args[0] as! VadMode
        let paramsArg = args[1] as! [String: Any?]
        do {
          let result = try api.startDialog(mode: modeArg, params: paramsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startDialogChannel.setMessageHandler(nil)
    }
    let releaseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_aliyun_nui.FlutterAliyunNuiHostApi.release\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      releaseChannel.setMessageHandler { _, reply in
        do {
          let result = try api.release()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      releaseChannel.setMessageHandler(nil)
    }
    let cancelDialogChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_aliyun_nui.FlutterAliyunNuiHostApi.cancelDialog\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelDialogChannel.setMessageHandler { _, reply in
        do {
          let result = try api.cancelDialog()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelDialogChannel.setMessageHandler(nil)
    }
    let stopDialogChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_aliyun_nui.FlutterAliyunNuiHostApi.stopDialog\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopDialogChannel.setMessageHandler { _, reply in
        do {
          let result = try api.stopDialog()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopDialogChannel.setMessageHandler(nil)
    }
  }
}
