// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.flutter_aliyun_nui

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object FlutterAliyunNuiHostApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class AudioState(val raw: Int) {
  STATE_OPEN(0),
  STATE_PAUSE(1),
  STATE_CLOSE(2);

  companion object {
    fun ofRaw(raw: Int): AudioState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class LogLevel(val raw: Int) {
  LOG_LEVEL_VERBOSE(0),
  LOG_LEVEL_DEBUG(1),
  LOG_LEVEL_INFO(2),
  LOG_LEVEL_WARNING(3),
  LOG_LEVEL_ERROR(4),
  LOG_LEVEL_NONE(5);

  companion object {
    fun ofRaw(raw: Int): LogLevel? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class VadMode(val raw: Int) {
  TYPE_UNKNOWN(0),
  TYPE_VAD(1),
  TYPE_P2T(2),
  TYPE_KWS(3),
  TYPE_PARALLEL(4),
  TYPE_KWS2PARALLEL(5),
  TYPE_AUTO_CONTINUAL(6),
  TYPE_KWS_CONTINUAL(7),
  TYPE_KWS2TALK(8),
  TYPE_ONLY_KWS(9);

  companion object {
    fun ofRaw(raw: Int): VadMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AsrResult (
  val finish: Boolean,
  val resultCode: Long,
  val asrResult: String,
  val allResponse: String,
  val value: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AsrResult {
      val finish = pigeonVar_list[0] as Boolean
      val resultCode = pigeonVar_list[1] as Long
      val asrResult = pigeonVar_list[2] as String
      val allResponse = pigeonVar_list[3] as String
      val value = pigeonVar_list[4] as Long
      return AsrResult(finish, resultCode, asrResult, allResponse, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      finish,
      resultCode,
      asrResult,
      allResponse,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is AsrResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return FlutterAliyunNuiHostApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class FlutterAliyunNuiHostApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AudioState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          LogLevel.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VadMode.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AsrResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AudioState -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is LogLevel -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is VadMode -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is AsrResult -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class FlutterAliyunNuiCallback(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by FlutterAliyunNuiCallback. */
    val codec: MessageCodec<Any?> by lazy {
      FlutterAliyunNuiHostApiPigeonCodec()
    }
  }
  fun onNuiNeedAudioData(bufferArg: ByteArray, lengthArg: Long, callback: (Result<Long>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_aliyun_nui.FlutterAliyunNuiCallback.onNuiNeedAudioData$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(bufferArg, lengthArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else if (it[0] == null) {
          callback(Result.failure(FlutterError("null-error", "Flutter api returned null value for non-null return value.", "")))
        } else {
          val output = it[0] as Long
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(FlutterAliyunNuiHostApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onNuiAudioStateChanged(stateArg: AudioState, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_aliyun_nui.FlutterAliyunNuiCallback.onNuiAudioStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(FlutterAliyunNuiHostApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onNuiEventCallback(eventArg: String, resultCodeArg: Long, kwsResultArg: String, asrResultArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_aliyun_nui.FlutterAliyunNuiCallback.onNuiEventCallback$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg, resultCodeArg, kwsResultArg, asrResultArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(FlutterAliyunNuiHostApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface FlutterAliyunNuiHostApi {
  fun initialize(params: Map<String, Any?>, saveLog: Boolean, logLevel: LogLevel): Long
  fun setParams(params: Map<String, Any?>): Long
  fun startDialog(mode: VadMode, params: Map<String, Any?>): Long
  fun release(): Long
  fun cancelDialog(): Long
  fun resumeDialog(): Long
  fun stopDialog(): Long

  companion object {
    /** The codec used by FlutterAliyunNuiHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      FlutterAliyunNuiHostApiPigeonCodec()
    }
    /** Sets up an instance of `FlutterAliyunNuiHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: FlutterAliyunNuiHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_aliyun_nui.FlutterAliyunNuiHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramsArg = args[0] as Map<String, Any?>
            val saveLogArg = args[1] as Boolean
            val logLevelArg = args[2] as LogLevel
            val wrapped: List<Any?> = try {
              listOf(api.initialize(paramsArg, saveLogArg, logLevelArg))
            } catch (exception: Throwable) {
              FlutterAliyunNuiHostApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_aliyun_nui.FlutterAliyunNuiHostApi.setParams$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramsArg = args[0] as Map<String, Any?>
            val wrapped: List<Any?> = try {
              listOf(api.setParams(paramsArg))
            } catch (exception: Throwable) {
              FlutterAliyunNuiHostApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_aliyun_nui.FlutterAliyunNuiHostApi.startDialog$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = args[0] as VadMode
            val paramsArg = args[1] as Map<String, Any?>
            val wrapped: List<Any?> = try {
              listOf(api.startDialog(modeArg, paramsArg))
            } catch (exception: Throwable) {
              FlutterAliyunNuiHostApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_aliyun_nui.FlutterAliyunNuiHostApi.release$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.release())
            } catch (exception: Throwable) {
              FlutterAliyunNuiHostApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_aliyun_nui.FlutterAliyunNuiHostApi.cancelDialog$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.cancelDialog())
            } catch (exception: Throwable) {
              FlutterAliyunNuiHostApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_aliyun_nui.FlutterAliyunNuiHostApi.resumeDialog$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.resumeDialog())
            } catch (exception: Throwable) {
              FlutterAliyunNuiHostApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_aliyun_nui.FlutterAliyunNuiHostApi.stopDialog$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.stopDialog())
            } catch (exception: Throwable) {
              FlutterAliyunNuiHostApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
